### ISSUE TITLE
Update readme with paper doi etc

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/antipsychotics-prescribing-during-COVID-19#40]
And do a code release

**Comment by acagreen17** [comment]
I have done the following:

- updated the readme by fixing the link to the project on jobserver (we no longer add paper dois here). 
- updated the status on jobserver from ongoing to completed and added the paper doi here (this is where we now add it)
- archived all the workspaces on jobserver
- tidied up the repo

Let me know if there's anything else needed @brianmackenna otherwise I will close this issue.

**Comment by brianmackenna** [comment]
Good work - thank you!

**Comment by brianmackenna** [comment]
Just looking - I also mean adding BMJ Mental Health DOI link

**Comment by acagreen17** [comment]
Not sure I understand...I've added the BMJ Mental Health DOI link to jobserver...do you think it should be somewhere else?

**Comment by brianmackenna** [comment]
In the readme - so if someone lands there they can see a) where to read more b) what to cite if they are that way inclined

**Comment by acagreen17** [comment]
As far as I'm aware we don't put it in the README anymore - it's all on jobserver. If you think it's important to have it in the README I can add it, but then probably worth discussing in an open channel as this is not the standard approach?

**Comment by brianmackenna** [comment]
I think it is!

Lets raise at next researchers meeting -  I may have missed something while I was away that was important.

**Comment by acagreen17** [comment]
I'm going to close this for now, but can revisit once discussed more widely.
